---
version: "3.4"
services:
  frontend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      # enable hot-reloading
      # mount checkout into container as bind-mount
      - ./:/opt/app
