---
version: "3.4"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8000:80
    volumes:
      - ./:/opt/app
    env_file:
      # Reuse .env from CRA
      - .env
