---
version: "3.4"
services:
  frontend:
    build:
      context: .
    ports:
      # allow override of published port
      - ${P_PORT:-8000}:80
    env_file:
      # Reuse .env from CRA
      - .env
