---
version: "3.4"
services:
  frontend:
    labels:
      # route by domain
      # todo: use as default route?
      #- "traefik.http.routers.frontend.rule=Host(`cosri.cirg.washington.edu`)"
      #- "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.rule=Host(`cosri.local`)"


  reverse_proxy:
    image: "traefik:v2.1.2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      # web admin
      - 8080:8080
    command:
      # enable Web UI
      #- --api.insecure=true
      # listen to docker events
      - --providers.docker
      #- --log.level=DEBUG

  facade:
    #image: 'containous/whoami:v1.3.0'
    image: script-fhir-facade_facade
    labels:
      # proxy all requests to MedicationOrder FHIR resource to SCRIPT Facade (providing MedicationOrder)
      - "traefik.http.routers.facade.rule=PathPrefix(`/v/r2/fhir/MedicationOrder`)"

      
    volumes:
      #- ./:/opt/app
      - /home/debian/src/cosri/SCRIPT-fhir-facade:/opt/app
    environment:
      SCRIPT_CLIENT_MUTUALLY_DEFINED: ${SCRIPT_CLIENT_MUTUALLY_DEFINED}
    ports:
      - 7000:7000
